#!/usr/bin/env node
// Generates both aspect-ratio compositions from one template so they never drift.
//   node scripts/build.mjs [9x16|4x5]   ->  index.html (+ meta.json) for that format
// One root composition per project (lint rule), so the generator swaps index.html
// between formats. 9:16 is the committed default. scripts/render-all.sh renders both.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

// ---- timing (seconds) — anchored to assets/sean-vo.transcript.json -----------
const T = {
  vo: 23.957,       // Sean VO file length
  cardWord: 21.75,  // "Tap the link and see if you qualify." — first word onset
  dissolve: 0.25,   // quick dissolve montage -> end card
  logoOut: 21.3,    // corner logo leaves just before the card
  total: 25.0,      // VO + ~1s breathing room on the card
};
T.cardIn = +(T.cardWord - 0.13).toFixed(2); // card fully up as he says "Tap"

const id = "ecomiq-sean-vo-ad";
const FORMATS = {
  "9x16": { W: 1080, H: 1920,
    logo: { top: 120, left: 84, width: 300 }, cardLogo: 640, pill: 44, gap: 96 },
  "4x5": { W: 1080, H: 1350,
    logo: { top: 64, left: 64, width: 260 }, cardLogo: 580, pill: 40, gap: 80 },
};

const html = ({ W, H, logo, cardLogo, pill, gap }) => {
  const cardDur = +(T.total - T.cardIn).toFixed(2);
  const pulseStart = T.cardWord + 1.0;
  const pulseCycle = 0.9; // one yoyo leg
  const pulseRepeats = Math.max(1, Math.floor((T.total - pulseStart) / pulseCycle) - 1);
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=${W}, height=${H}" />
    <title>${id}</title>
    <!-- GENERATED by scripts/build.mjs — edit the generator, not this file -->
    <!-- GSAP vendored locally — CDN cert-fails in the render env and freezes renders -->
    <script src="assets/vendor/gsap.min.js"></script>
    <link rel="stylesheet" href="assets/brand-tokens.css" />
    <style>
      /* LOCAL fonts — no network dependency at render time (latin subset) */
      @font-face { font-family: 'Rethink Sans'; font-style: normal; font-weight: 400 800;
        font-display: block; src: url(assets/fonts/RethinkSans.woff2) format('woff2'); }
      @font-face { font-family: 'Hedvig Letters Serif'; font-style: normal; font-weight: 400;
        font-display: block; src: url(assets/fonts/HedvigLettersSerif.woff2) format('woff2'); }
      * { margin: 0; padding: 0; box-sizing: border-box; }
      html, body { width: ${W}px; height: ${H}px; overflow: hidden;
        background: var(--brand-bg); font-family: 'Rethink Sans', system-ui, sans-serif; color: var(--brand-text); }

      /* Montage: 9:16 source, scale + pad (contain) — native fit on 9:16, navy pillars on 4:5 */
      #bg { position: absolute; inset: 0; background: var(--brand-navy); }
      #montage-wrap { position: absolute; inset: 0; z-index: 1; }
      #montage { width: 100%; height: 100%; object-fit: contain; display: block; }

      /* Corner logo — positioned non-clip wrapper keeps it pinned (see docs/LESSONS.md) */
      #logo-wrap { position: absolute; z-index: 5; top: ${logo.top}px; left: ${logo.left}px; width: ${logo.width}px; }
      #logo { display: block; width: 100%; height: auto;
        filter: drop-shadow(0 2px 14px rgba(6,40,76,.55)); }

      /* End card */
      #card { position: absolute; inset: 0; z-index: 10;
        background: radial-gradient(80% 45% at 50% 30%, rgba(156,212,255,.12) 0%, rgba(6,40,76,0) 60%), var(--brand-navy); }
      #card-bloom { position: absolute; left: 50%; top: 62%; width: 900px; height: 520px;
        transform: translate(-50%, -50%); background: var(--brand-gradient-2);
        filter: blur(120px); opacity: .28; border-radius: 50%; }
      #card-stage { position: absolute; inset: 0; display: flex; flex-direction: column;
        align-items: center; justify-content: center; gap: ${gap}px; padding: 10%; }
      #card-logo { width: ${cardLogo}px; height: auto; display: block; }
      #cta { display: flex; align-items: center; gap: 18px; font-weight: 700; font-size: ${pill}px;
        letter-spacing: -.01em; color: var(--brand-white); background: var(--brand-flame);
        padding: 30px 64px; border-radius: 999px; box-shadow: 0 24px 72px -18px rgba(255,76,50,.65); }
      #cta svg { width: ${Math.round(pill * 0.8)}px; height: ${Math.round(pill * 0.8)}px; }
    </style>
  </head>
  <body>
    <div id="root" data-composition-id="${id}" data-start="0" data-duration="${T.total}" data-width="${W}" data-height="${H}">
      <div id="bg" class="clip" data-start="0" data-duration="${T.total}" data-track-index="0"></div>

      <!-- Montage visuals (own audio stripped at prep; muted per render contract) -->
      <div id="montage-wrap">
        <video id="montage" data-start="0" data-duration="${T.cardIn + T.dissolve}" data-track-index="1"
          src="assets/montage.mp4" muted playsinline></video>
      </div>

      <div id="logo-wrap">
        <img id="logo" class="clip" data-start="0" data-duration="${T.logoOut + 0.3}" data-track-index="2"
          src="assets/ecomiq-logo-white.svg" alt="EcomIQ" />
      </div>

      <div id="card" class="clip" data-start="${T.cardIn}" data-duration="${cardDur}" data-track-index="4">
        <div id="card-bloom"></div>
        <div id="card-stage">
          <img id="card-logo" src="assets/ecomiq-logo-white.svg" alt="EcomIQ" />
          <div id="cta">Link Below
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"><path d="M12 5v14M5 12l7 7 7-7"/></svg>
          </div>
        </div>
      </div>

      <!-- Sean VO: the spine of the edit -->
      <audio id="vo" data-start="0" data-duration="${T.vo}" data-track-index="3"
        src="assets/sean-vo.wav" data-volume="1"></audio>
    </div>
    <script>
      window.__timelines = window.__timelines || {};
      const tl = gsap.timeline({ paused: true });
      // corner logo in, then out just before the card
      tl.fromTo("#logo", { opacity: 0, y: -16 }, { opacity: 1, y: 0, duration: .5, ease: "power3.out" }, .2)
        .to("#logo", { opacity: 0, duration: .3, ease: "power1.in" }, ${T.logoOut});
      // quick dissolve into the end card, landing on "Tap the link…"
      tl.fromTo("#card", { opacity: 0 }, { opacity: 1, duration: ${T.dissolve}, ease: "power1.inOut" }, ${T.cardIn})
        .fromTo("#card-logo", { opacity: 0, scale: .92 }, { opacity: 1, scale: 1, duration: .55, ease: "expo.out" }, ${T.cardWord})
        .fromTo("#cta", { opacity: 0, y: 36, scale: .86 }, { opacity: 1, y: 0, scale: 1, duration: .5, ease: "back.out(1.7)" }, ${+(T.cardWord + 0.3).toFixed(2)})
        .to("#cta", { scale: 1.05, duration: ${pulseCycle}, ease: "sine.inOut", yoyo: true, repeat: ${pulseRepeats} }, ${pulseStart});
      tl.set({}, {}, ${T.total}); // pad to data-duration
      window.__timelines["${id}"] = tl;
    </script>
  </body>
</html>
`;
};

const key = process.argv[2] || "9x16";
const f = FORMATS[key];
if (!f) { console.error(`Unknown format '${key}'. Use: ${Object.keys(FORMATS).join(" | ")}`); process.exit(1); }
writeFileSync(join(root, "index.html"), html(f));
const metaPath = join(root, "meta.json");
const meta = JSON.parse(readFileSync(metaPath, "utf8"));
writeFileSync(metaPath, JSON.stringify({ ...meta, width: f.W, height: f.H }, null, 2) + "\n");
console.log(`wrote index.html  ${key}  (${f.W}x${f.H}, ${T.total}s, card @ ${T.cardIn}s)`);
