#!/usr/bin/env node
/**
 * derive-45.mjs — generate the 4:5 cut (bf-45.html) from the 9:16 master
 * (index.html), so the two ratios can never drift apart structurally.
 *
 *   node scripts/derive-45.mjs        -> compositions/bf-45.html
 *
 * Everything except geometry is shared: same beats, same GSAP timeline, same
 * copy, same numbers. This script swaps the frame size, the composition id and
 * the A-roll source, then appends a type-scale override block.
 *
 * Why the overrides: 4:5 has 1350px of height against 9:16's 1920 — 70% of the
 * vertical budget — so the type steps down and the lower panel tightens. In the
 * 4:5 crop Sean's face sits between roughly 10% and 50% of frame height, so the
 * panel is anchored below 58% and never covers him. --safe-bottom is the
 * reserved subtitle band; nothing is drawn inside it in either ratio.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const src = readFileSync(resolve(root, 'index.html'), 'utf8');

const swaps = [
  ['width=1080, height=1920', 'width=1080, height=1350'],
  ['Black Friday Profit Plan (9:16)', 'Black Friday Profit Plan (4:5)'],
  ['width: 1080px; height: 1920px;', 'width: 1080px; height: 1350px;'],
  ['· 9:16 (1080x1920 @30fps) · 39.0s', '· 4:5 (1080x1350 @30fps) · 39.0s'],
  ['assets/aroll-916.mp4', 'assets/aroll-45.mp4'],
  ['assets/broll-a-916.mp4', 'assets/broll-a-45.mp4'],
  ['assets/broll-b-916.mp4', 'assets/broll-b-45.mp4'],
  ['data-composition-id="ecomiq-black-friday"', 'data-composition-id="ecomiq-black-friday-45"'],
  ['data-height="1920"', 'data-height="1350"'],
  ["window.__timelines['ecomiq-black-friday']", "window.__timelines['ecomiq-black-friday-45']"],
];

let out = src;
for (const [from, to] of swaps) {
  if (!out.includes(from)) throw new Error(`derive-45: anchor not found -> ${from}`);
  out = out.split(from).join(to);
}

const overrides = `
      /* ================= 4:5 (1080x1350) geometry overrides =================
         Generated by scripts/derive-45.mjs — edit there, not here.
         70% of the 9:16 vertical budget, so the type scale steps down and the
         lower panel starts below 58% of frame height (clear of Sean's face). */
      :root {
        --pad: 64px;
        --logo-w: 176px;
        --safe-bottom: 150px;   /* reserved subtitle band — 11% of 1350 */
        --row-fs: 28px;
        --title-fs: 88px;
      }
      #logo-wrap { top: 52px; }
      .eyebrow { font-size: 23px; }
      .rule { width: 88px; height: 5px; margin: 18px 0 26px; }

      /* 4:5 has far less height, and the subtitle band takes 150 of it, so the
         panel is compacted again to stay clear of Sean's face (~50% of frame). */
      .panel-inner { border-radius: 26px; padding: 26px 34px 24px; }
      .panel .eyebrow { font-size: 21px; }
      .panel-rule { margin: 12px 0 16px; }
      .row { padding: 4px 0; }
      .divider { margin: 10px 0 3px; }
      .result .l { font-size: 26px; }
      .result .v { font-size: 48px; }
      .result .pct { font-size: 23px; }

      .tile { padding: 20px 18px 18px; border-radius: 18px; }
      .tile .k { font-size: 18px; min-height: 44px; }
      .tile .n { font-size: 52px; margin-top: 8px; }

      #card-contrast h2 { font-size: 60px; margin-bottom: 32px; }
      .col { padding: 26px 24px 24px; border-radius: 22px; }
      .col .h { font-size: 21px; }
      .col .big { font-size: 50px; margin: 10px 0 16px; }
      .col .kv { font-size: 23px; padding: 5px 0; }
      .col .kv b { font-size: 28px; }
      #contrast-foot { margin-top: 30px; font-size: 30px; gap: 12px; }
      #contrast-foot i { font-size: 38px; }

      #checklist-panel { border-radius: 26px; padding: 30px 34px 26px; }
      #card-checklist h2 { font-size: 62px; margin-bottom: 36px; }
      .item { padding: 15px 0; gap: 20px; }
      .tick { width: 54px; height: 54px; border-radius: 15px; }
      .tick svg { width: 28px; height: 28px; }
      .item .t { font-size: 34px; }


      #ec-logo { width: 330px; margin-bottom: 38px; }
      #ec-eyebrow { font-size: 23px; margin-bottom: 22px; }
      #ec-sub { margin-top: 26px; font-size: 30px; }
      #ec-pill { margin-top: 42px; font-size: 35px; padding: 27px 62px; }
    </style>`;

out = out.replace('    </style>', overrides);

writeFileSync(resolve(root, 'compositions', 'bf-45.html'), out);
console.log('✓ compositions/bf-45.html written from index.html (1080x1350, comp id ecomiq-black-friday-45)');
