#!/usr/bin/env node
/**
 * derive-45.mjs — generate the 4:5 cut (bf-45.html) from the 9:16 master
 * (index.html), so the two ratios can never drift apart structurally.
 *
 *   node scripts/derive-45.mjs        -> compositions/bf-45.html
 *
 * Everything except geometry is shared: same beats, same GSAP timeline, same
 * copy, same numbers. This script swaps the frame size, the composition id and
 * the A-roll source, then appends a type-scale override block.
 *
 * Why the overrides: 4:5 has 1350px of height against 9:16's 1920 — 70% of the
 * vertical budget — so the type steps down and the lower panel tightens. In the
 * 4:5 crop Sean's face sits between roughly 10% and 50% of frame height, so the
 * panel is anchored below 58% and never covers him. --safe-bottom is the
 * reserved subtitle band; nothing is drawn inside it in either ratio.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const src = readFileSync(resolve(root, 'index.html'), 'utf8');

const swaps = [
  ['width=1080, height=1920', 'width=1080, height=1350'],
  ['Black Friday Profit Plan (9:16)', 'Black Friday Profit Plan (4:5)'],
  ['width: 1080px; height: 1920px;', 'width: 1080px; height: 1350px;'],
  ['· 9:16 (1080x1920 @30fps) · 39.0s', '· 4:5 (1080x1350 @30fps) · 39.0s'],
  ['assets/aroll-916.mp4', 'assets/aroll-45.mp4'],
  ['assets/broll-b-916.mp4', 'assets/broll-b-45.mp4'],
  ['data-composition-id="ecomiq-black-friday"', 'data-composition-id="ecomiq-black-friday-45"'],
  ['data-height="1920"', 'data-height="1350"'],
  ["window.__timelines['ecomiq-black-friday']", "window.__timelines['ecomiq-black-friday-45']"],
];

let out = src;
for (const [from, to] of swaps) {
  if (!out.includes(from)) throw new Error(`derive-45: anchor not found -> ${from}`);
  out = out.split(from).join(to);
}

const overrides = `
      /* ================= 4:5 (1080x1350) geometry overrides =================
         Generated by scripts/derive-45.mjs — edit there, not here.
         70% of the 9:16 vertical budget, so the type scale steps down and the
         question panel tightens. In the 4:5 crop Sean's face sits between
         roughly 10% and 50% of frame height; the panel is anchored above the
         subtitle band and, fully grown, still starts below ~63%. */
      :root {
        --pad: 64px;
        --logo-w: 176px;
        --safe-bottom: 150px;   /* reserved subtitle band — 11% of 1350 */
        --q-fs: 32px;
        --title-fs: 88px;
      }
      #logo-wrap { top: 52px; }
      .eyebrow { font-size: 23px; }

      .panel-inner { border-radius: 26px; padding: 28px 28px 24px; }
      .panel .eyebrow { font-size: 21px; }
      .panel-rule { margin: 12px 0 14px; }
      .q-in { padding: 10px 0; gap: 18px; }
      .q-n { width: 46px; height: 46px; border-radius: 13px; font-size: 23px; }
      .q-t { padding-top: 4px; }

      #ec-logo { width: 330px; margin-bottom: 38px; }
      #ec-eyebrow { font-size: 23px; margin-bottom: 22px; }
      #ec-sub { margin-top: 26px; font-size: 30px; }
      #ec-pill { margin-top: 42px; font-size: 35px; padding: 27px 62px; }
    </style>`;

out = out.replace('    </style>', overrides);

writeFileSync(resolve(root, 'compositions', 'bf-45.html'), out);
console.log('✓ compositions/bf-45.html written from index.html (1080x1350, comp id ecomiq-black-friday-45)');
