#!/usr/bin/env python3
"""
gen-ratios.py — emit compositions/square.html (1:1) and compositions/meta45.html
(4:5) from index.html (9:16).

index.html is the single source of truth for the edit: timeline, beat anchors,
markup and animation are identical across all three ratios. Only the geometry
block between the @@GEO@@ / @@ENDGEO@@ markers differs, plus the composition id
and the montage bed filename.

Run from the PROJECT folder after editing index.html:

    python3 scripts/gen-ratios.py && npx hyperframes lint

Track indices are offset per variant (0-20 / 30-50 / 60-80) because
`hyperframes lint` merges sibling root compositions into one graph and would
otherwise report bogus duplicate_audio_track overlaps. Track indices are
per-composition, so the offset costs nothing.
"""
import pathlib
import re
import sys

HERE = pathlib.Path(__file__).resolve().parent.parent
SRC = HERE / "index.html"

VARIANTS = {
    "compositions/square.html": dict(
        cid="ecomiq-how-it-works-ad-square", label="1:1", W=1080, H=1080,
        bed="montage-11.mp4", tbase=30,
        note="1:1 geometry (1080x1080)",
        geo="""        --ov-top: 56px;
        --ov-side: 52px;
        --bug-w: 240px;
        --pip-d: 220px;
        --card-logo: 497px;   /* 46% of 1080 */
        --card-gap: 30px;

        --g-top: 316px;       /* bug/PiP end at 276 */
        --g-bot: 150px;
        --g-side: 72px;
        --g-gap: 22px;
        --g-h2: 50px;
        --g-h3: 33px;
        --g-body: 25px;
        --g-num: 96px;
        --g-big: 132px;
        --g-node: 250px;
        --g-slam: 78px;
        --lt-bot: 150px;
        --g-tile: 120px;
        --w-row: 150px;
        --w-logo-w: 250px;
        --w-logo-h: 82px;"""),
    "compositions/meta45.html": dict(
        cid="ecomiq-how-it-works-ad-45", label="4:5", W=1080, H=1350,
        bed="montage-45.mp4", tbase=60,
        note="4:5 geometry (1080x1350) — picture derived from the 1:1 master",
        geo="""        --ov-top: 70px;
        --ov-side: 54px;
        --bug-w: 250px;
        --pip-d: 230px;
        --card-logo: 497px;   /* 46% of 1080 */
        --card-gap: 32px;

        --g-top: 344px;       /* bug/PiP end at 300 */
        --g-bot: 180px;
        --g-side: 78px;
        --g-gap: 27px;
        --g-h2: 58px;
        --g-h3: 38px;
        --g-body: 28px;
        --g-num: 112px;
        --g-big: 160px;
        --g-node: 320px;
        --g-slam: 88px;
        --lt-bot: 210px;
        --g-tile: 148px;
        --w-row: 172px;
        --w-logo-w: 280px;
        --w-logo-h: 92px;"""),
}


def build(src: str, v: dict) -> str:
    t = src

    # --- geometry block (the only per-ratio difference) ---
    geo_re = re.compile(r"(/\* @@GEO@@).*?(/\* @@ENDGEO@@ \*/)", re.S)
    if not geo_re.search(t):
        sys.exit("index.html is missing the @@GEO@@ / @@ENDGEO@@ markers")
    block = (
        f"/* @@GEO@@ {v['note']} — generated by scripts/gen-ratios.py from\n"
        f"         index.html. Do NOT edit this file directly: edit index.html\n"
        f"         and the geometry table in scripts/gen-ratios.py, then re-run it. */\n"
        f"      html, body {{ width: {v['W']}px; height: {v['H']}px; }}\n"
        f"      :root {{\n{v['geo']}\n      }}\n"
        f"      /* @@ENDGEO@@ */"
    )
    t = geo_re.sub(lambda _: block, t)

    # --- identity + canvas ---
    t = t.replace("ecomiq-how-it-works-ad — 9:16", f"ecomiq-how-it-works-ad — {v['label']}")
    t = t.replace('data-composition-id="ecomiq-how-it-works-ad"',
                  f'data-composition-id="{v["cid"]}"')
    t = t.replace('window.__timelines["ecomiq-how-it-works-ad"]',
                  f'window.__timelines["{v["cid"]}"]')
    t = t.replace('content="width=1080, height=1920"',
                  f'content="width={v["W"]}, height={v["H"]}"')
    t = t.replace('data-width="1080"\n      data-height="1920"',
                  f'data-width="{v["W"]}"\n      data-height="{v["H"]}"')

    # --- picture bed for this ratio ---
    t = t.replace("montage-916.mp4", v["bed"])

    # --- track offset (see module docstring) ---
    t = re.sub(r'data-track-index="(\d+)"',
               lambda m: f'data-track-index="{int(m.group(1)) + v["tbase"]}"', t)

    # Asset paths stay ROOT-relative: compositions are served with the project
    # root as their base URL, even when rendered via -c compositions/<f>.html.
    # `../assets/...` lints as invalid_parent_traversal_in_asset_path.
    assert "../assets/" not in t
    return t


def main() -> None:
    src = SRC.read_text()
    for rel, v in VARIANTS.items():
        out = HERE / rel
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(build(src, v))
        print(f"wrote {rel}  ({v['label']} {v['W']}x{v['H']}, tracks "
              f"{v['tbase']}-{v['tbase'] + 20}, bed {v['bed']})")


if __name__ == "__main__":
    main()
